# Generated by Django 4.2.5 on 2023-09-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
