# Generated by Django 4.2.5 on 2023-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='group',
            field=models.CharField(choices=[('management', 'Management'), ('all', 'All'), ('accounting', 'Accounting'), ('sales', 'Sales'), ('tech', 'Tech')], default='all', max_length=100),
        ),
    ]
