# Generated by Django 4.2.5 on 2023-10-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userinfo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='group',
            field=models.CharField(choices=[('management', 'Management'), ('accounting', 'Accounting'), ('sales', 'Sales'), ('tech', 'Tech')], default='tech', max_length=100),
        ),
    ]
