# Generated by Django 4.2.5 on 2023-10-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
