# Generated by Django 4.2.5 on 2023-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_userinfo_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='group',
            field=models.CharField(choices=[('management', 'Management'), ('accounting', 'Accounting'), ('sales', 'Sales'), ('tech', 'Tech'), ('restricted', 'Restricted')], default='restricted', max_length=100),
        ),
    ]
