# Generated by Django 4.2.5 on 2023-09-26 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('group', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=100)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2023, 10, 11, 18, 38, 49, 523755))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
