# Generated by Django 4.2.5 on 2023-09-26 18:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 18, 47, 12, 25636)),
        ),
        migrations.CreateModel(
            name='Version_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2023, 10, 11, 18, 47, 12, 25636))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='System.files')),
            ],
        ),
    ]
