# Generated by Django 4.2.5 on 2023-09-26 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_alter_files_expire_date_alter_files_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='version',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='version_control',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 19, 7, 16, 975221)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 19, 7, 16, 975221)),
        ),
    ]
