# Generated by Django 4.2.5 on 2023-09-28 03:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_files_description_files_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='version_control',
            name='pre_ver_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='System.version_control'),
        ),
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 3, 13, 14, 254016)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 3, 13, 14, 254016)),
        ),
    ]
