# Generated by Django 4.2.5 on 2023-10-01 23:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0006_files_extension_files_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version_control',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 23, 44, 24, 883027)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 23, 44, 24, 883027)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='file',
            field=models.FileField(upload_to='files/version/'),
        ),
    ]
