# Generated by Django 4.2.5 on 2023-10-02 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_version_control_uploaded_by_alter_files_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version_control',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='version_control',
            name='version',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 0, 17, 57, 152289)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 0, 17, 57, 152289)),
        ),
    ]
