# Generated by Django 4.2.5 on 2023-10-02 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_version_control_org_name_version_control_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 1, 33, 55, 642409)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 1, 33, 55, 642409)),
        ),
    ]
