# Generated by Django 4.2.5 on 2023-10-02 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_alter_files_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 1, 35, 37, 141802)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 1, 35, 37, 141802)),
        ),
    ]
