# Generated by Django 4.2.5 on 2023-10-02 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_version_control_group_alter_files_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='new_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='version_control',
            name='new_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 1, 58, 19, 84877)),
        ),
        migrations.AlterField(
            model_name='version_control',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 1, 58, 19, 84877)),
        ),
    ]
