# Generated by Django 4.2.5 on 2023-10-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_remove_files_description_remove_files_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='size',
        ),
    ]
