# Generated by Django 4.2.5 on 2023-10-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0015_alter_files_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
