# Generated by Django 4.2.5 on 2023-10-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_files_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='version_control',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
