# Generated by Django 4.2.5 on 2023-10-23 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0017_version_control_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('Action', models.CharField(max_length=100)),
                ('level', models.IntegerField(default='0')),
                ('message', models.CharField(max_length=1000)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
