# Generated by Django 4.2.5 on 2023-10-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_security_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version_control',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
