# Generated by Django 4.2.5 on 2023-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0021_temp_ocr_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='version_control',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
